### ISSUE TITLE
Please consider using "traitsui.editors.api" instead of "traitsui.editors" to import editor factories

### ISSUE THREAD

**Issue by rahulporuri** [WeberSynBioLab/optoConfig-96#1]
https://github.com/WeberSynBioLab/optoConfig-96/blob/60a6abdcbbb9f69014458784f9505e4aa0908ebf/optoConfig96/load.py#L24

Ref https://github.com/enthought/traitsui/issues/1617

**Comment by osthomas** [comment]
Thanks for the heads-up!
Fixed with 4e6926097b5780abbcd91230931c2d11cec59c96
